parameters:
  makaira.connect.id: 'makaira_oxid-connect-frontend'
  makaira.connect-essential.id: 'makaira_oxid-connect-essential'

services:
  _defaults:
    public: true
    autowire: true
    autoconfigure: true
    bind:
      OxidEsales\EshopCommunity\Internal\Framework\Module\Facade\ModuleSettingServiceInterface $connectSettings: '@Makaira\OxidConnect\Helper\ModuleSettings'
      OxidEsales\Eshop\Core\ViewConfig $oxidViewConfig: "@oxid.view-config"
      string $filterParameterName: '@=service("Makaira\\OxidConnect\\Helper\\ModuleSettings").getString("makaira_connect_url_param")'
      bool $cookieBannerEnabled: '@=service("Makaira\\OxidConnect\\Helper\\ModuleSettings").getBoolean("makaira_cookie_banner_enabled")'
      bool $personalizationEnabled: '@=service("Makaira\\OxidConnect\\Helper\\ModuleSettings").getBoolean("makaira_connect_personalization_enabled")'
      string $baseUri: '@=service("Makaira\\OxidConnect\\Helper\\ModuleSettings").getString("makaira_application_url")'
      array $fieldMapping: '@=service("Makaira\\OxidConnect\\Helper\\ModuleSettings").getCollection("makaira_sort_field_mapping")'
      string $instance: '@=service("Makaira\\OxidConnect\\Helper\\ModuleSettings").getString("makaira_instance")'
      string $apiKey: '@=service("Makaira\\OxidConnect\\Helper\\ModuleSettings").getString("makaira_connect_secret", parameter("makaira.connect-essential.id"))'
      bool $useCategoryInheritance: '@=service("Makaira\\OxidConnect\\Helper\\ModuleSettings").getBoolean("makaira_connect_category_inheritance")'
      string $categoryAggregationId: '@=service("Makaira\\OxidConnect\\Helper\\ModuleSettings").getString("makaira_connect_categorytree_id")'
      string $moduleId: "%makaira.connect.id%"

  Makaira\OxidConnect\:
    resource: 'src/'
    exclude: 'src/{Domain,Exception,Oxid,Controller,Personalization,Http/Request.php,HttpClient}'

  oxid.utils-object:
    class: OxidEsales\Eshop\Core\UtilsObject
    factory: 'OxidEsales\Eshop\Core\UtilsObject::getInstance'

  oxid.view-config:
    class: OxidEsales\Eshop\Core\ViewConfig
    factory: [ "@oxid.utils-object", "oxNew" ]
    arguments:
      - 'OxidEsales\Eshop\Core\ViewConfig'

  Makaira\OxidConnect\Http\Middleware\MiddlewareStackInterface:
    alias: Makaira\OxidConnect\Http\Middleware\MiddlewareStack

  Makaira\OxidConnect\Http\Middleware\MiddlewareStack:
    calls:
      - addMiddleware: [ '@Makaira\OxidConnect\Http\Middleware\BaseUri', 0 ]
      - addMiddleware: [ '@Makaira\OxidConnect\Http\Middleware\Instance', 0 ]
      - addMiddleware: [ '@Makaira\OxidConnect\Http\Middleware\Tracing', 0 ]
      - addMiddleware: [ '@Makaira\OxidConnect\Http\Middleware\SortFieldMapping', 1 ]
      - addMiddleware: [ '@Makaira\OxidConnect\Http\Middleware\Json', 2 ]
      - addMiddleware: [ '@Makaira\OxidConnect\Http\Middleware\Signature', 3 ]

  Makaira\HttpClient:
    alias: Makaira\OxidConnect\Http\Client

  Makaira\OxidConnect\Http\Client:
    bind:
      $timeout: '@=service("Makaira\\OxidConnect\\Helper\\ModuleSettings").getInteger("makaira_connect_timeout")'
      $cache: '@cache.http-client'

  cache.http-client:
    class: 'Symfony\Component\Cache\Adapter\ArrayAdapter'
    bind:
      $maxLifetime: 60
      $maxItems: 20
      $defaultLifetime: 10

  Makaira\OxidConnect\Service\RecommendationHandler:
    bind:
      $httpClient: '@Makaira\HttpClient'

  Makaira\OxidConnect\Twig\AssetsExtension:
    tags:
      - { name: "twig.extension" }

  Makaira\OxidConnect\Helper\OxidSettingsInterface:
    alias: Makaira\OxidConnect\Helper\OxidSettings

  Makaira\OxidConnect\Helper\OxidSettings:
    factory: [ null, 'create' ]
