name: Release

on:
  workflow_call:
  push:
    branches: [ "[0-9]+.x", "stable" ]
  pull_request:
    branches: [ "[0-9]+.x", "stable" ]
    types: [ opened, synchronize, reopened ]

env:
  PACKAGE_NAME: 'makaira/oxid-connect-essential'
  MODULE_PATH: 'makaira/oxid-connect-essential'

jobs:
  release:
    name: Create a new release
    runs-on: ubuntu-latest
    steps:
      - name: Clone code repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install npm dependencies
        run: yarn

      - name: Semantic release
        run: yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GIT_AUTHOR_NAME: ${{ secrets.GIT_USERNAME }}
          GIT_AUTHOR_EMAIL: ${{ secrets.GIT_EMAIL }}
          GIT_COMMITTER_NAME: ${{ secrets.GIT_USERNAME }}
          GIT_COMMITTER_EMAIL: ${{ secrets.GIT_EMAIL }}
          GIT_CREDENTIALS: ${{ secrets.GIT_CREDENTIALS }}
